"""server side defaults

Revision ID: 9509c3c67de8
Revises: 89e0b6964c47
Create Date: 2026-08-20 11:38:37.506973+09:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9509c3c67de8'
down_revision: Union[str, None] = '89e0b6964c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'source',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'upload'"),
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'added_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'skipped_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('income_profile', 'monthly_net',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('income_profile', 'extra',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('mail_message', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'pending'"),
               existing_nullable=False,
               schema='budget')
    op.alter_column('transaction', 'billing_month_known',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('transaction', 'fee',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='budget')
    op.alter_column('app_user', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'active'"),
               existing_nullable=False,
               schema='identity')
    op.alter_column('email_verification', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='identity')
    op.alter_column('user_credential', 'algorithm',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pbkdf2_sha256'"),
               existing_nullable=False,
               schema='identity')
    op.alter_column('api_quota_usage', 'call_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='ops')
    op.alter_column('api_quota_usage', 'error_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='ops')
    op.alter_column('batch_run', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'running'"),
               existing_nullable=False,
               schema='ops')
    op.alter_column('batch_run', 'items_processed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='ops')
    op.alter_column('page_view_daily', 'view_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='ops')
    op.alter_column('holding', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'KRW'"),
               existing_nullable=False,
               schema='portfolio')
    op.alter_column('interest_run', 'time_unit',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'month'"),
               existing_nullable=False,
               schema='realestate')
    op.alter_column('interest_run', 'region_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='realestate')
    op.alter_column('interest_run', 'source',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'naver_api_hub'"),
               existing_nullable=False,
               schema='realestate')
    op.alter_column('region_month_stat', 'deal_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='realestate')
    op.alter_column('region_month_stat', 'is_provisional',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='realestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region_month_stat', 'is_provisional',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='realestate')
    op.alter_column('region_month_stat', 'deal_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='realestate')
    op.alter_column('interest_run', 'source',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False,
               schema='realestate')
    op.alter_column('interest_run', 'region_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='realestate')
    op.alter_column('interest_run', 'time_unit',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False,
               schema='realestate')
    op.alter_column('holding', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False,
               schema='portfolio')
    op.alter_column('page_view_daily', 'view_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               schema='ops')
    op.alter_column('batch_run', 'items_processed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='ops')
    op.alter_column('batch_run', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False,
               schema='ops')
    op.alter_column('api_quota_usage', 'error_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               schema='ops')
    op.alter_column('api_quota_usage', 'call_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               schema='ops')
    op.alter_column('user_credential', 'algorithm',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False,
               schema='identity')
    op.alter_column('email_verification', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='identity')
    op.alter_column('app_user', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False,
               schema='identity')
    op.alter_column('transaction', 'fee',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('transaction', 'billing_month_known',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('mail_message', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('income_profile', 'extra',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('income_profile', 'monthly_net',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'skipped_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'added_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('import_batch', 'source',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    op.alter_column('category', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='budget')
    # ### end Alembic commands ###
