"""region migration

Revision ID: 03139a655c31
Revises: 7704a5c48f1d
Create Date: 2026-08-20 17:34:51.587322+09:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03139a655c31'
down_revision: Union[str, None] = '7704a5c48f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_batch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.String(length=6), nullable=False),
    sa.Column('from_sido', sa.String(length=2), nullable=False),
    sa.Column('to_sido', sa.String(length=2), nullable=False),
    sa.Column('row_cnt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_batch')),
    sa.UniqueConstraint('year_month', 'from_sido', 'to_sido', name='uq_migration_batch_year_month_from_sido_to_sido'),
    schema='realestate'
    )
    op.create_table('region_migration',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.String(length=6), nullable=False),
    sa.Column('from_code', sa.String(length=10), nullable=False),
    sa.Column('to_code', sa.String(length=10), nullable=False),
    sa.Column('from_name', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('to_name', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('total_cnt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('male_cnt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('female_cnt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('age_0_19', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('age_20_34', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('age_35_49', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('age_50_64', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('age_65_plus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_cnt >= 0', name=op.f('ck_region_migration_total_cnt_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_migration')),
    sa.UniqueConstraint('year_month', 'from_code', 'to_code', name='uq_region_migration_year_month_from_code_to_code'),
    schema='realestate'
    )
    op.create_index('ix_region_migration_from_month', 'region_migration', ['from_code', 'year_month'], unique=False, schema='realestate')
    op.create_index('ix_region_migration_to_month', 'region_migration', ['to_code', 'year_month'], unique=False, schema='realestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_region_migration_to_month', table_name='region_migration', schema='realestate')
    op.drop_index('ix_region_migration_from_month', table_name='region_migration', schema='realestate')
    op.drop_table('region_migration', schema='realestate')
    op.drop_table('migration_batch', schema='realestate')
    # ### end Alembic commands ###
