"""region commerce

Revision ID: 7704a5c48f1d
Revises: cf999600ae08
Create Date: 2026-08-20 17:00:56.584855+09:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7704a5c48f1d'
down_revision: Union[str, None] = 'cf999600ae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_commerce',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('category_code', sa.String(length=4), nullable=False),
    sa.Column('category_name', sa.String(length=32), nullable=False),
    sa.Column('store_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('store_count >= 0', name=op.f('ck_region_commerce_store_count_non_negative')),
    sa.ForeignKeyConstraint(['region_id'], ['realestate.region.id'], name=op.f('fk_region_commerce_region_id_region'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_commerce')),
    sa.UniqueConstraint('region_id', 'category_code', name='uq_region_commerce_region_id_category_code'),
    schema='realestate'
    )
    op.create_index('ix_region_commerce_region', 'region_commerce', ['region_id'], unique=False, schema='realestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_region_commerce_region', table_name='region_commerce', schema='realestate')
    op.drop_table('region_commerce', schema='realestate')
    # ### end Alembic commands ###
