"""initial schema

Revision ID: afb6047a7f4d
Revises: 
Create Date: 2026-08-20 11:35:22.147538+09:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'afb6047a7f4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_category')),
    schema='budget'
    )
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default=sa.text("'system'"), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('active','locked','disabled')", name=op.f('ck_app_user_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    schema='identity'
    )
    op.create_index('uq_app_user_username_lower', 'app_user', [sa.literal_column('lower(username)')], unique=True, schema='identity')
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event')),
    schema='identity'
    )
    op.create_index('ix_audit_event_actor_occurred', 'audit_event', ['actor', 'occurred_at'], unique=False, schema='identity')
    op.create_index('ix_audit_event_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False, schema='identity')
    op.create_index('ix_audit_event_occurred_at', 'audit_event', ['occurred_at'], unique=False, schema='identity')
    op.create_table('email_verification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification')),
    schema='identity'
    )
    op.create_index('ix_email_verification_email_expires', 'email_verification', ['email', 'expires_at'], unique=False, schema='identity')
    op.create_table('security',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('wics_sector', sa.String(length=64), nullable=True),
    sa.Column('board', sa.String(length=32), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security')),
    sa.UniqueConstraint('market', 'ticker', name='uq_security_market_ticker'),
    schema='market'
    )
    op.create_index('ix_security_name', 'security', ['name'], unique=False, schema='market')
    op.create_table('api_quota_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('daily_limit', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_quota_usage')),
    sa.UniqueConstraint('provider', 'usage_date', name='uq_api_quota_usage_provider_usage_date'),
    schema='ops'
    )
    op.create_table('batch_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('running','success','failed','skipped')", name=op.f('ck_batch_run_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_run')),
    schema='ops'
    )
    op.create_index('ix_batch_run_job_started', 'batch_run', ['job_name', 'started_at'], unique=False, schema='ops')
    op.create_table('dataset_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=64), nullable=False),
    sa.Column('storage', sa.String(length=16), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_snapshot')),
    schema='ops'
    )
    op.create_index('ix_dataset_snapshot_name_built', 'dataset_snapshot', ['dataset_name', 'built_at'], unique=False, schema='ops')
    op.create_table('page_view_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('view_name', sa.String(length=32), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_view_daily')),
    sa.UniqueConstraint('view_name', 'view_date', name='uq_page_view_daily_view_name_view_date'),
    schema='ops'
    )
    op.create_table('interest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anchor_keyword', sa.String(length=64), nullable=False),
    sa.Column('time_unit', sa.String(length=8), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('region_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interest_run')),
    schema='realestate'
    )
    op.create_table('region',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lawd_cd', sa.String(length=5), nullable=False),
    sa.Column('sido', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('geocode_source', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region')),
    sa.UniqueConstraint('lawd_cd', name='uq_region_lawd_cd'),
    schema='realestate'
    )
    op.create_table('card',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('card_key', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('cycle_start_day', sa.SmallInteger(), nullable=True),
    sa.Column('cycle_end_day', sa.SmallInteger(), nullable=True),
    sa.Column('pay_day', sa.SmallInteger(), nullable=True),
    sa.Column('pay_offset', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cycle_end_day BETWEEN 1 AND 31', name=op.f('ck_card_cycle_end_day_range')),
    sa.CheckConstraint('cycle_start_day BETWEEN 1 AND 31', name=op.f('ck_card_cycle_start_day_range')),
    sa.CheckConstraint('pay_day BETWEEN 1 AND 31', name=op.f('ck_card_pay_day_range')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_card_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card')),
    sa.UniqueConstraint('user_id', 'card_key', name='uq_card_user_id_card_key'),
    schema='budget'
    )
    op.create_table('import_batch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('issuer', sa.String(length=32), nullable=True),
    sa.Column('billing_month', sa.String(length=7), nullable=True),
    sa.Column('parsed_by', sa.String(length=32), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default=sa.text("'system'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_import_batch_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    schema='budget'
    )
    op.create_index('ix_import_batch_user_created', 'import_batch', ['user_id', 'created_at'], unique=False, schema='budget')
    op.create_table('income_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('monthly_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('extra', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_income_profile_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_profile')),
    sa.UniqueConstraint('user_id', 'effective_from', name='uq_income_profile_user_id_effective_from'),
    schema='budget'
    )
    op.create_table('mail_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issuer', sa.String(length=32), nullable=True),
    sa.Column('billing_month', sa.String(length=7), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','imported','discarded','locked','skipped')", name=op.f('ck_mail_message_status')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_mail_message_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_message')),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_mail_message_user_id_message_id'),
    schema='budget'
    )
    op.create_index('ix_mail_message_user_status', 'mail_message', ['user_id', 'status'], unique=False, schema='budget')
    op.create_table('merchant_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['budget.category.code'], name=op.f('fk_merchant_rule_category_code_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_merchant_rule_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rule')),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_merchant_rule_user_id_merchant_key'),
    schema='budget'
    )
    op.create_table('user_credential',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('iterations > 0', name=op.f('ck_user_credential_iterations_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_user_credential_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_credential')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_credential_user_id')),
    schema='identity'
    )
    op.create_table('company_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('representative', sa.String(length=64), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('corp_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market', 'ticker'], ['market.security.market', 'market.security.ticker'], name='fk_company_profile_security', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_profile')),
    sa.UniqueConstraint('market', 'ticker', name='uq_company_profile_market_ticker'),
    schema='market'
    )
    op.create_table('holding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('avg_price >= 0', name=op.f('ck_holding_avg_price_non_negative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_holding_quantity_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_holding_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding')),
    sa.UniqueConstraint('user_id', 'market', 'ticker', name='uq_holding_user_id_market_ticker'),
    schema='portfolio'
    )
    op.create_table('watch_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_watch_item_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_item')),
    sa.UniqueConstraint('user_id', 'market', 'ticker', name='uq_watch_item_user_id_market_ticker'),
    schema='portfolio'
    )
    op.create_table('wealth_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('married', sa.Boolean(), nullable=True),
    sa.Column('homeless', sa.Boolean(), nullable=True),
    sa.Column('has_child', sa.Boolean(), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('goal_years', sa.SmallInteger(), nullable=True),
    sa.Column('holdings_horizon', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_wealth_profile_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wealth_profile')),
    sa.UniqueConstraint('user_id', name='uq_wealth_profile_user_id'),
    schema='portfolio'
    )
    op.create_table('interest_point',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('ratio_to_anchor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['realestate.region.id'], name=op.f('fk_interest_point_region_id_region'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['realestate.interest_run.id'], name=op.f('fk_interest_point_run_id_interest_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interest_point')),
    sa.UniqueConstraint('run_id', 'region_id', 'period', name='uq_interest_point_run_id_region_id_period'),
    schema='realestate'
    )
    op.create_index('ix_interest_point_region_period', 'interest_point', ['region_id', 'period'], unique=False, schema='realestate')
    op.create_table('region_month_stat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('year_month', sa.String(length=6), nullable=False),
    sa.Column('trade_type', sa.String(length=8), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_monthly_rent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trade_type IN ('sale','jeonse','wolse')", name=op.f('ck_region_month_stat_trade_type')),
    sa.CheckConstraint('deal_count >= 0', name=op.f('ck_region_month_stat_deal_count_non_negative')),
    sa.ForeignKeyConstraint(['region_id'], ['realestate.region.id'], name=op.f('fk_region_month_stat_region_id_region'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_month_stat')),
    sa.UniqueConstraint('region_id', 'year_month', 'trade_type', name='uq_region_month_stat_region_id_year_month_trade_type'),
    schema='realestate'
    )
    op.create_index('ix_region_month_stat_region_trade_month', 'region_month_stat', ['region_id', 'trade_type', 'year_month'], unique=False, schema='realestate')
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('billing_month_known', sa.Boolean(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('charged', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tx_type', sa.String(length=16), nullable=False),
    sa.Column('installment_months', sa.SmallInteger(), nullable=True),
    sa.Column('installment_seq', sa.SmallInteger(), nullable=True),
    sa.Column('category_code', sa.String(length=32), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("tx_type IN ('일시불','할부','현금서비스','해외','취소')", name=op.f('ck_transaction_tx_type')),
    sa.CheckConstraint('(installment_months IS NULL) = (installment_seq IS NULL)', name=op.f('ck_transaction_installment_pair')),
    sa.ForeignKeyConstraint(['card_id'], ['budget.card.id'], name=op.f('fk_transaction_card_id_card'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_code'], ['budget.category.code'], name=op.f('fk_transaction_category_code_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['budget.import_batch.id'], name=op.f('fk_transaction_import_batch_id_import_batch'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.app_user.id'], name=op.f('fk_transaction_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_transaction_user_id_fingerprint'),
    schema='budget'
    )
    op.create_index('ix_transaction_user_billing_month', 'transaction', ['user_id', 'billing_month'], unique=False, schema='budget')
    op.create_index('ix_transaction_user_merchant_key', 'transaction', ['user_id', 'merchant_key'], unique=False, schema='budget')
    op.create_index('ix_transaction_user_txn_date', 'transaction', ['user_id', 'txn_date'], unique=False, schema='budget')
    op.create_table('region_month_area_stat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('month_stat_id', sa.BigInteger(), nullable=False),
    sa.Column('area_bucket', sa.String(length=16), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['month_stat_id'], ['realestate.region_month_stat.id'], name=op.f('fk_region_month_area_stat_month_stat_id_region_month_stat'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_month_area_stat')),
    sa.UniqueConstraint('month_stat_id', 'area_bucket', name='uq_region_month_area_stat_month_stat_id_area_bucket'),
    schema='realestate'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_month_area_stat', schema='realestate')
    op.drop_index('ix_transaction_user_txn_date', table_name='transaction', schema='budget')
    op.drop_index('ix_transaction_user_merchant_key', table_name='transaction', schema='budget')
    op.drop_index('ix_transaction_user_billing_month', table_name='transaction', schema='budget')
    op.drop_table('transaction', schema='budget')
    op.drop_index('ix_region_month_stat_region_trade_month', table_name='region_month_stat', schema='realestate')
    op.drop_table('region_month_stat', schema='realestate')
    op.drop_index('ix_interest_point_region_period', table_name='interest_point', schema='realestate')
    op.drop_table('interest_point', schema='realestate')
    op.drop_table('wealth_profile', schema='portfolio')
    op.drop_table('watch_item', schema='portfolio')
    op.drop_table('holding', schema='portfolio')
    op.drop_table('company_profile', schema='market')
    op.drop_table('user_credential', schema='identity')
    op.drop_table('merchant_rule', schema='budget')
    op.drop_index('ix_mail_message_user_status', table_name='mail_message', schema='budget')
    op.drop_table('mail_message', schema='budget')
    op.drop_table('income_profile', schema='budget')
    op.drop_index('ix_import_batch_user_created', table_name='import_batch', schema='budget')
    op.drop_table('import_batch', schema='budget')
    op.drop_table('card', schema='budget')
    op.drop_table('region', schema='realestate')
    op.drop_table('interest_run', schema='realestate')
    op.drop_table('page_view_daily', schema='ops')
    op.drop_index('ix_dataset_snapshot_name_built', table_name='dataset_snapshot', schema='ops')
    op.drop_table('dataset_snapshot', schema='ops')
    op.drop_index('ix_batch_run_job_started', table_name='batch_run', schema='ops')
    op.drop_table('batch_run', schema='ops')
    op.drop_table('api_quota_usage', schema='ops')
    op.drop_index('ix_security_name', table_name='security', schema='market')
    op.drop_table('security', schema='market')
    op.drop_index('ix_email_verification_email_expires', table_name='email_verification', schema='identity')
    op.drop_table('email_verification', schema='identity')
    op.drop_index('ix_audit_event_occurred_at', table_name='audit_event', schema='identity')
    op.drop_index('ix_audit_event_entity', table_name='audit_event', schema='identity')
    op.drop_index('ix_audit_event_actor_occurred', table_name='audit_event', schema='identity')
    op.drop_table('audit_event', schema='identity')
    op.drop_index('uq_app_user_username_lower', table_name='app_user', schema='identity')
    op.drop_table('app_user', schema='identity')
    op.drop_table('category', schema='budget')
    # ### end Alembic commands ###
